version: 2

sources:
  - name: staging
    database: dtc-de-377105
    schema: trips_data_all

    tables:
      - name: external_green_tripdata
      - name: external_yellow_tripdata
      